### ISSUE TITLE
notes can be modified by others via view embed!?!?1??

### ISSUE THREAD

**Issue by neonplayanson** [Loco-CTO/Rystal-V6-Experiments#105]
this i mean
![image](https://github.com/user-attachments/assets/788e249d-b11d-4f1e-b7f0-d6cfddce0f61)

**Comment by Rin-Suzuk1** [comment]
again 😅

**Comment by neonplayanson** [comment]
i dont think was authgaurd ever implemented into this in the first place? correct me if im wrong

**Comment by Rin-Suzuk1** [comment]
> i dont think was authgaurd ever implemented into this in the first place? correct me if im wrong

no 😗

**Comment by Rin-Suzuk1** [comment]
loco made it without testing it 😗😗😗😗

**Comment by neonplayanson** [comment]
sounds legit to me
